### ISSUE TITLE
Confirm the reason why there are so many frame with only "B" activated?

### ISSUE THREAD

**Issue by huskydoge** [rafaelcp/smbdataset#3]
Hi author, I noticed that there are many frames accompanied by "B" only, and the Mario is not in the Fire Flower Giant Mario mode. Is this expected?

Is this some kind of habit of the player to press the button "B" only?

**Comment by rafaelcp** [comment]
Yeah, B is also used for running, so I have the habit of keeping it pressed most of the time :)
